title: Error page
icon: alert

columns:
  - width: 1/2
    sections:
    fields:

      #Floating Nav
      floatingNavHeadline:
        label: Floating nav
        type: headline
        numbered: false
      floatingNavSwitch:
        label: Floating nav?
        type: toggle
        width: 1/2
        text: 
          - "no"
          - "yes"
      floatingNavInfoPositive:
        label: Results in
        type: info
        text: "**Floating nav: ** nav will hide/show show on scroll"
        theme: positive
        width: 1/2
        when:
          floatingNavSwitch: yes
      floatingNavInfoNegative:
        label: Results in
        type: info
        text: "**Default nav: ** nav will stick to top of page"
        theme: negative
        width: 1/2
        when:
          floatingNavSwitch: no
      line-z:
        type: line

      #Error
      defaultHeadline:
        label: Error page
        type: headline
      errorPageTitle:
        label: Title
        type: text
      errorPageParagraph:
        label: Paragraph
        type: writer
        inline: true