title: Error page
icon: alert

columns:
  - width: 1/2
    sections:
    fields:

      #Floating Nav
      floatingNavHeadline:
        label: Floating nav
        type: headline
        numbered: false
      floatingNavSwitch:
        extends: fields/f-nav-switch
      floatingNavInfoPositive:
        extends: fields/f-nav-info-pos
      floatingNavInfoNegative:
        extends: fields/f-nav-info-neg
      line-z:
        type: line

      #Error
      defaultHeadline:
        label: Error page
        type: headline
      errorPageTitle:
        label: Title
        type: text
      errorPageParagraph:
        label: Paragraph
        type: writer
        inline: true