title: Error page
icon: alert

columns:
  - width: 1/2
    sections:
    fields:

      defaultHeadline:
        label: Error page
        type: headline
      errorPageTitle:
        label: Title
        type: text
      errorPageParagraph:
        label: Paragraph
        type: writer
        inline: true