title: Service
icon: store



columns:

  - width: 1/4
    sections:
    fields:
      service:
        label: Service selector
        type: radio
        options:
          websiteApps: Website & -apps
          seo: SEO
          photography: Photography
          graphicDesign: Graphic design
          conceptAdvice: Concept & advice

  #STARTERKIT TEXT CONTENT
  - width: 2/4
    sections:
    fields:

      #Floating Nav
      floatingNavHeadline:
        label: Floating nav
        type: headline
        numbered: false
      floatingNavSwitch:
        extends: fields/f-nav-switch
      floatingNavInfoPositive:
        extends: fields/f-nav-info-pos
      floatingNavInfoNegative:
        extends: fields/f-nav-info-neg
      line-z:
        type: line

      #Header
      headerHeadline:
        label: Header
        type: headline
        numbered: true
      headerTitle:
        label: Title
        type: text
      headerParagraph:
        label: Paragraph
        type: writer
        inline: true
      
      #button 
      headerButton:
        extends: fields/button
      line-a:
        type: line
      
      #Steps
      stepsHeadline:
        label: Steps/Kits
        type: headline
        numbered: true
      stepsInfo:
        label:
        type: info
        text: Leave empty on **photography** detail page
        theme: negative
        when:
          service: photography
      stepsTitle:
        label: Title
        type: text
      stepsParagraph:
        label: Paragraph
        type: writer
        inline: true
      steps:
        label: Steps
        type: structure
        columns:
          number:
            width: 1/8
          title:
            width: 2/8
          explanation:
            width: 5/8
        fields:
          number:
            label: Number
            type: text
          title:
            label: Title
            type: text
          explanation:
            label: Explanation
            type: writer
            inline: true
          features:
            label: Features
            type: structure
            fields:
              feature:
                label: Feature
                type: writer
          stepButton:
            extends: fields/button
      line-b:
        type: line
      
      #Carousels
      carouselsHeadline:
        label: Carousels
        type: headline
        numbered: true
        when:
          service: photography
      carousels:
        label: Carousels
        type: structure
        when:
          service: photography
        fields:
          carouselTitle:
            label: Carousel title
            type: text
          carouselImagesWebp:
            label: Carousel images .webp
            type: files
            layout: cards
          carouselImagesPng:
            label: Carousel images .png
            type: files
            layout: cards
      line-c:
        type: line
        when:
          service: photography

      
      #CTA
      ctaHeadline:
        label: CTA
        type: headline
        numbered: true
      ctaText:
        label: CTA text
        type: writer
        inline: true
      ctaFeatures:
        label: CTA Features
        type: structure
        fields:
          feature:
            label: Feature
            type: writer
      
      #buttons  
      ctaButtons:
        extends: fields/buttons
      line-d:
        type: line
        when:
          service: websiteApps
      
      #WebsiteCases
      casesHeadline:
        label: Website cases
        type: headline
        numbered: true
        when:
          service: websiteApps
      casesTitle:
        label: Title
        type: text
        when:
          service: websiteApps
      cases:
        label: Website cases
        type: pages
        query: site.find('projecten')
        when:
          service: websiteApps
  


  #STARTERKIT TEXT CONTENT
  - width: 1/4
    sections:
    fields:
      websiteImgHeadline:
        label: Service images
        type: headline
        numbered: false
      headerImgWebp:
        label: Header img .webp
        type: files
        max: 1
        layout: cards
      headerImgPng:
        label: Header img .png
        type: files
        max: 1
        layout: cards
      line-e:
        type: line
      
      ctaImgWebp:
        label: CTA img .webp
        type: files
        max: 1
        layout: cards
        width: 1/2
      ctaImgPng:
        label: CTA img .png
        type: files
        max: 1
        layout: cards
        width: 1/2