title: Present Online Website

tabs:
  menu:
    icon: dashboard

    columns:

      #pages
      - width: 1/3
        sections:
          listed:
            headline: Listed pages
            type: pages
            status: listed
            image: icon
              back: black
          unlisted:
            headline: Unlisted pages
            type: pages
            status: unlisted
            image: icon
              back: black
          drafts:
            headline: Drafts
            type: pages
            status: draft
            image: icon
              back: black
      
      #text content
      - width: 2/3
        sections:
        fields:
          menuHeadline:
            label: Menu
            type: headline
            numbered: true
          navigationLinks:
            label: Menu items
            type: structure
            columns:
              anchor:
                width: 1/3
              page:
                width: 1/3
              section:
                width: 1/3
            fields:
              anchor:
                label: Anchor
                type: text
              page:
                label: Destination
                type: pages
                image: icon
              section:
                label: id
                type: text
          line-a:
            type: line



          #logos
          logosHeadline:
            label: Logos
            type: headline
            numbered: true
          logoLight:
            label: Licht logo
            type: files
            max: 1
            layout: cards
            width: 1/3
          logoDark:
            label: Donker logo
            type: files
            max: 1
            layout: cards
            width: 1/3


  
  metaContent:
    icon: text
    columns:

      #meta text content
      - width: 1/2
        sections:
        fields:
          metaContentHeadline:
            label: Meta content
            type: headline
            numbered: true
          metaTitle:
            label: Meta title
            type: text
          metaDescription:
            label: Meta description
            type: writer
            inline: true

          

      #preview image
      - width: 1/2
        sections:
        fields:
          previewImageHeadline:
            label: Preview image
            type: headline
            numbered: true
          previewImage:
            label: Preview image
            type: files
            layout: cards
            cover: true
            ratio: 2/1
            max: 1
  


  contact:
    icon: email

    columns:

      #socials
      - width: 1/2
        sections:
        fields:
          socialsHeadline:
            label: Social media
            type: headline
            numbered: true
          socials:
            label:
            type: structure
            columns:
              social:
                label: Platform
                width: 1/4
              url:
                width: 3/4
            fields:
              social:
                type: select
                options:
                  facebook: Facebook
                  instagram: Instagram
                  linkedin: LinkedIn
                  twitter: Twitter
                  youtube: Youtube
                  website: Andere website
              url:
                type: url
      
      #socials
      - width: 1/2
        sections:
        fields:
          contactHeadline:
            label: Contact information
            type: headline
            numbered: true
          telephone:
            label: Telephone number
            type: text
          email:
            label: Contact email
            type: text

  


  footer:
    icon: grid-bottom

    columns:

      #socials
      - width: 1/4
        sections:
        fields:
          footerHeadline:
            label: Footer sections
            type: headline
            numbered: false
      
      #socials
      - width: 3/4
        sections:
        fields:
          introHeadline:
            label: Introduction
            type: headline
            numbered: true
          introParagraph:
            label: Short introduction
            type: writer
            inline: true
          line-b:
            type: line
          
          sitemapHeadline:
            label: Sitemap
            type: headline
            numbered: true
          sitemap:
            label: Sitemap
            type: structure
            columns:
              anchor:
                width: 1/3
              page:
                width: 1/3
              section:
                width: 1/3
            fields:
              anchor:
                label: Anchor
                type: text
              page:
                label: Destination
                type: pages
                image: icon
              section:
                label: id
                type: text
          line-c:
            type: line

          servicesHeadline:
            label: Services
            type: headline
            numbered: true
          services:
            label: Services
            type: structure
            columns:
              anchor:
                width: 1/3
              page:
                width: 1/3
              section:
                width: 1/3
            fields:
              anchor:
                label: Anchor
                type: text
              page:
                label: Destination
                type: pages
                image: icon
              section:
                label: id
                type: text
          line-d:
            type: line


          copyrightHeadline:
            label: Copyright & BTW
            type: headline
            numbered: true
          copyright:
            label: Copyright
            type: text
          btwNr:
            label: BTW number
            type: text